FROM debian:latest
MAINTAINER Lan Tian <lantian@lantian.pub>

ENV ASF_VERSION=3.0.2.2
RUN apt-get update -q \
    && apt-get upgrade -y \
    && apt-get install -y curl libunwind8 gettext unzip wget \
    && apt-get clean \
    && mkdir /asf \
    && cd /asf \
    && wget -O asf.zip https://github.com/JustArchi/ArchiSteamFarm/releases/download/${ASF_VERSION}/ASF-linux-x64.zip \
    && unzip asf.zip \
    && rm asf.zip \
    && chmod +x ArchiSteamFarm
WORKDIR /asf
HEALTHCHECK CMD curl 127.0.0.1:1242
ENTRYPOINT /asf/ArchiSteamFarm --server
