FROM multiarch/alpine:i386-edge
LABEL Lan Tian "lantian@lantian.pub"
RUN mkdir /usr/log && mkdir /run/php \
    && apk -q --no-cache search php7- | egrep -v "(apache|dev)" | xargs apk -s --no-cache add
ADD www.conf /etc/php7/php-fpm.d/www.conf
ADD php.ini /etc/php7/php.ini
ADD php-fpm.conf /etc/php7/php-fpm.conf
EXPOSE 9000
ENTRYPOINT ["php-fpm7"]
