FROM multiarch/alpine:armhf-edge
LABEL Lan Tian "lantian@lantian.pub"
RUN mkdir /usr/log && mkdir /run/php \
    && apk --no-cache add php7 \
    && apk search php7- | grep -v php7-7 | awk -F'-' '{print $1 "-" $2}' | xargs apk --no-cache add
ADD www.conf /etc/php7/php-fpm.d/www.conf
ADD php.ini /etc/php7/php.ini
ADD php-fpm.conf /etc/php7/php-fpm.conf
EXPOSE 9000
ENTRYPOINT ["php-fpm7"]
